# Generated by Django 2.1.5 on 2019-02-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.IntegerField()),
                ('message_parent_id', models.IntegerField()),
                ('message_body', models.TextField(max_length=1024)),
                ('message_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MessageAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('image_icon_url', models.URLField()),
            ],
        ),
    ]
