# Generated by Django 2.1.5 on 2019-02-15 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_data', '0003_auto_20190214_1737'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageAuthor',
        ),
    ]
